"""Add previous years vacation days fields

Revision ID: 22cda11fc77b
Revises: fbf30684ca05
Create Date: 2025-04-17 10:30:16.069305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cda11fc77b'
down_revision = 'fbf30684ca05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande_vacances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annee_precedente', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annee_avant_precedente', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annee_avant_avant_precedente', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annee_selection', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande_vacances', schema=None) as batch_op:
        batch_op.drop_column('annee_selection')
        batch_op.drop_column('annee_avant_avant_precedente')
        batch_op.drop_column('annee_avant_precedente')
        batch_op.drop_column('annee_precedente')

    # ### end Alembic commands ###
