"""Add previous years vacation tracking

Revision ID: 97969edabc6a
Revises: 22cda11fc77b
Create Date: 2025-04-17 10:43:15.089645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97969edabc6a'
down_revision = '22cda11fc77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande_vacances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_previous_years', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('previous_year_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('previous_year_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('previous_year_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('previous_years_details', sa.Text(), nullable=True))
        batch_op.drop_column('annee_avant_precedente')
        batch_op.drop_column('annee_avant_avant_precedente')
        batch_op.drop_column('annee_precedente')
        batch_op.drop_column('annee_selection')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande_vacances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annee_selection', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('annee_precedente', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('annee_avant_avant_precedente', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('annee_avant_precedente', sa.INTEGER(), nullable=True))
        batch_op.drop_column('previous_years_details')
        batch_op.drop_column('previous_year_3')
        batch_op.drop_column('previous_year_2')
        batch_op.drop_column('previous_year_1')
        batch_op.drop_column('use_previous_years')

    # ### end Alembic commands ###
