"""initial migration

Revision ID: a332ca6c192f
Revises: 
Create Date: 2025-03-18 11:13:51.914037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a332ca6c192f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autorisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autorisation', schema=None) as batch_op:
        batch_op.drop_column('signature_data')

    # ### end Alembic commands ###
