"""Add annee_exercice field to demande_vacances

Revision ID: a64493514828
Revises: 97969edabc6a
Create Date: 2025-04-20 10:15:44.815379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64493514828'
down_revision = '97969edabc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande_vacances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annee_exercice', sa.Integer(), nullable=True))
        batch_op.drop_column('previous_year_1')
        batch_op.drop_column('previous_year_2')
        batch_op.drop_column('use_previous_years')
        batch_op.drop_column('previous_year_3')
        batch_op.drop_column('previous_years_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande_vacances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_years_details', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('previous_year_3', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('use_previous_years', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('previous_year_2', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('previous_year_1', sa.INTEGER(), nullable=True))
        batch_op.drop_column('annee_exercice')

    # ### end Alembic commands ###
