"""Add residuel_clarification column to demande_vacances

Revision ID: fbf30684ca05
Revises: 412d53755b3d
Create Date: 2025-04-17 09:44:53.665598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf30684ca05'
down_revision = '412d53755b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande_vacances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residuel_clarification', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande_vacances', schema=None) as batch_op:
        batch_op.drop_column('residuel_clarification')

    # ### end Alembic commands ###
